/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.SecretariaModel;
import controller.AdministradorDAO;
import controller.ConsultaDAO;
import controller.MedicoDAO;
import controller.PacienteDAO;
import controller.SecretariaDAO;
import java.awt.CardLayout;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ConsultaModel;
import model.MedicoModel;
import model.PacienteModel;

/**
 *
 * @author Neto
 */
public class telaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form telaAdministrador
     */
    public telaAdministrador() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    
    public void preencheTabela() throws SQLException{
        SecretariaDAO sdao = null;
        DefaultTableModel tblSec = (DefaultTableModel) tblSecretarias.getModel();
        
        try {
            sdao = new SecretariaDAO();
            for(SecretariaModel s : sdao.listarSecretarias()){
                Object [] dados = {s.getCod(),s.getRg(),s.getNome(),s.getCpf(),s.getEndereco(),s.getSexo()};
                tblSec.addRow(dados);
            }
        } catch (SQLException ex) {
            Logger.getLogger(telaAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
    
    
    public void preencheTabelaMedico() throws SQLException{
        MedicoDAO mdao = null;
        DefaultTableModel tblMed = (DefaultTableModel) tblMedico.getModel();
        
        try {
            mdao = new MedicoDAO();
            for(MedicoModel m : mdao.listarMedicos()){
                Object [] dados = {m.getCrm(), m.getNome(), m.getTelefone(), m.getCpf(),m.getRg(),m.getEndereco(), m.getSexo()};
                tblMed.addRow(dados);
            }
        } catch (SQLException ex) {
            Logger.getLogger(telaAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
    
    public void preencheTabelaPaciente() throws SQLException{
        PacienteDAO pdao = null;
        DefaultTableModel tblPac = (DefaultTableModel) tblPacientes.getModel();
        
        try {
            pdao = new PacienteDAO();
            for(PacienteModel p : pdao.listarPacientes()){
                Object [] dados = {p.getNome(), p.getTelefone(), p.getCpf(), p.getRg(),p.getEndereco(),p.getSexo()};
                tblPac.addRow(dados);
            }
        } catch (SQLException ex) {
            Logger.getLogger(telaAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
    
    public void cadastraSecretariaTabela() throws SQLException{
        SecretariaDAO sdao = null;
        DefaultTableModel tblSec = (DefaultTableModel) tblSecretarias.getModel();
        
        try {
            sdao = new SecretariaDAO();
            for(SecretariaModel s : sdao.listarUltimaSecretarias()){
                Object [] dados = {s.getCod(),s.getRg(),s.getNome(),s.getCpf(),s.getEndereco(),s.getSexo()};
                tblSec.addRow(dados);
            }
        } catch (SQLException ex) {
            Logger.getLogger(telaAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        inicio = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        secretarias = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSecretarias = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        rg = new javax.swing.JTextField();
        endereco = new javax.swing.JTextField();
        btnCadastro = new javax.swing.JButton();
        Nome = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sexo = new javax.swing.JComboBox();
        senha = new javax.swing.JPasswordField();
        cpf = new javax.swing.JFormattedTextField();
        btnEdita = new javax.swing.JButton();
        btnApaga = new javax.swing.JButton();
        cod = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        confirmSenha = new javax.swing.JPasswordField();
        medicos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMedico = new javax.swing.JTable();
        pacientes = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPacientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        logout.setBackground(new java.awt.Color(255, 51, 51));
        logout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Sair");
        logout.setFocusable(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/admin2.png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Medicos");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Secretarias");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Pacientes");
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(9, 9, 9)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setLayout(new java.awt.CardLayout());

        inicio.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bemvindo.png"))); // NOI18N
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout inicioLayout = new javax.swing.GroupLayout(inicio);
        inicio.setLayout(inicioLayout);
        inicioLayout.setHorizontalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
                .addGap(77, 77, 77))
        );
        inicioLayout.setVerticalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(inicio, "card4");

        secretarias.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tblSecretarias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD", "RG", "Nome", "CPF", "Endereço", "Sexo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        try {
            preencheTabela();
        } catch (SQLException ex) {
            Logger.getLogger(telaAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblSecretarias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSecretariasMouseClicked(evt);
            }
        });
        tblSecretarias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblSecretariasKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblSecretariasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tblSecretariasKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tblSecretarias);
        if (tblSecretarias.getColumnModel().getColumnCount() > 0) {
            tblSecretarias.getColumnModel().getColumn(0).setResizable(false);
            tblSecretarias.getColumnModel().getColumn(1).setResizable(false);
            tblSecretarias.getColumnModel().getColumn(2).setResizable(false);
            tblSecretarias.getColumnModel().getColumn(3).setResizable(false);
            tblSecretarias.getColumnModel().getColumn(4).setResizable(false);
            tblSecretarias.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("CONTROLE DE SECRETÁRIAS");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Login:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Senha:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("CPF:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("RG:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Endereço:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Sexo:");

        rg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgActionPerformed(evt);
            }
        });

        btnCadastro.setBackground(new java.awt.Color(0, 204, 51));
        btnCadastro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCadastro.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastro.setText("CADASTRAR");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Nome:");

        sexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino", "Outro" }));

        try {
            cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnEdita.setBackground(new java.awt.Color(51, 153, 255));
        btnEdita.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEdita.setForeground(new java.awt.Color(255, 255, 255));
        btnEdita.setText("EDITAR");
        btnEdita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditaActionPerformed(evt);
            }
        });

        btnApaga.setBackground(new java.awt.Color(255, 51, 51));
        btnApaga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnApaga.setForeground(new java.awt.Color(255, 255, 255));
        btnApaga.setText("APAGAR");
        btnApaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagaActionPerformed(evt);
            }
        });

        cod.setText("COD");
        cod.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Confirmação de Senha:");

        javax.swing.GroupLayout secretariasLayout = new javax.swing.GroupLayout(secretarias);
        secretarias.setLayout(secretariasLayout);
        secretariasLayout.setHorizontalGroup(
            secretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secretariasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(secretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(secretariasLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(secretariasLayout.createSequentialGroup()
                        .addGroup(secretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(secretariasLayout.createSequentialGroup()
                                .addGap(20, 144, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(secretariasLayout.createSequentialGroup()
                                .addGroup(secretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(secretariasLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel3))
                                    .addGroup(secretariasLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(secretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(secretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(secretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secretariasLayout.createSequentialGroup()
                                .addGroup(secretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(secretariasLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(secretariasLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secretariasLayout.createSequentialGroup()
                                .addGroup(secretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(secretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(confirmSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(endereco))))
                        .addGap(89, 89, 89)
                        .addGroup(secretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdita, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnApaga, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)))
                .addContainerGap())
        );
        secretariasLayout.setVerticalGroup(
            secretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secretariasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(secretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(secretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(secretariasLayout.createSequentialGroup()
                        .addGroup(secretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(secretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(secretariasLayout.createSequentialGroup()
                                .addGroup(secretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(secretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addGroup(secretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(secretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(confirmSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(secretariasLayout.createSequentialGroup()
                        .addComponent(btnCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdita, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnApaga, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );

        jPanel2.add(secretarias, "telaDefault");

        tblMedico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CRM", "Nome", "Telefone", "CPF", "RG", "Endereço", "Sexo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        try {
            preencheTabelaMedico();
        } catch (SQLException ex) {
            Logger.getLogger(telaAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        jScrollPane2.setViewportView(tblMedico);
        if (tblMedico.getColumnModel().getColumnCount() > 0) {
            tblMedico.getColumnModel().getColumn(0).setResizable(false);
            tblMedico.getColumnModel().getColumn(1).setResizable(false);
            tblMedico.getColumnModel().getColumn(2).setResizable(false);
            tblMedico.getColumnModel().getColumn(3).setResizable(false);
            tblMedico.getColumnModel().getColumn(4).setResizable(false);
            tblMedico.getColumnModel().getColumn(5).setResizable(false);
            tblMedico.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout medicosLayout = new javax.swing.GroupLayout(medicos);
        medicos.setLayout(medicosLayout);
        medicosLayout.setHorizontalGroup(
            medicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1037, Short.MAX_VALUE)
                .addContainerGap())
        );
        medicosLayout.setVerticalGroup(
            medicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(medicos, "telaConsulta");

        tblPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Telefone", "CPF", "RG", "Endereço", "Sexo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        try {
            preencheTabelaPaciente();
        } catch (SQLException ex) {
            Logger.getLogger(telaAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        jScrollPane3.setViewportView(tblPacientes);
        if (tblPacientes.getColumnModel().getColumnCount() > 0) {
            tblPacientes.getColumnModel().getColumn(0).setResizable(false);
            tblPacientes.getColumnModel().getColumn(1).setResizable(false);
            tblPacientes.getColumnModel().getColumn(2).setResizable(false);
            tblPacientes.getColumnModel().getColumn(3).setResizable(false);
            tblPacientes.getColumnModel().getColumn(4).setResizable(false);
            tblPacientes.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout pacientesLayout = new javax.swing.GroupLayout(pacientes);
        pacientes.setLayout(pacientesLayout);
        pacientesLayout.setHorizontalGroup(
            pacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pacientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1037, Short.MAX_VALUE)
                .addContainerGap())
        );
        pacientesLayout.setVerticalGroup(
            pacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pacientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(pacientes, "telaPacientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        dispose();
        login telaP = new login();
        telaP.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout c2 = (CardLayout) jPanel2.getLayout();
        c2.show(jPanel2, "telaConsulta");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout) jPanel2.getLayout();
        c1.show(jPanel2, "telaDefault");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        CardLayout c3 = (CardLayout) jPanel2.getLayout();
        c3.show(jPanel2, "telaPacientes");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        // TODO add your handling code here:
        SecretariaModel secretaria = new SecretariaModel();
        SecretariaDAO secDAO = null;
        try {
            secDAO = new SecretariaDAO();
        } catch (SQLException ex) {
            Logger.getLogger(telaAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        List<SecretariaModel> secs = new ArrayList<>();
        
        AdministradorDAO adminDAO = null;
        try {
            adminDAO = new AdministradorDAO();
        } catch (SQLException ex) {
            Logger.getLogger(telaAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        secretaria.setNome(Nome.getText());
        secretaria.setCpf(cpf.getText());
        secretaria.setEndereco(endereco.getText());
        secretaria.setLogin(login.getText());
        secretaria.setRg(rg.getText());
        secretaria.setSenha(senha.getText());
        secretaria.setSexo((String) sexo.getSelectedItem());
        
        try {
            secs = secDAO.listarSecretarias();
        } catch (SQLException ex) {
            Logger.getLogger(telaAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            if(senha.getText().equals(confirmSenha.getText())){
                adminDAO.cadastrarSecretarias(secretaria);
                JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso!");
                cadastraSecretariaTabela();
            }else {
                JOptionPane.showMessageDialog(null, "A senha e confirmação de senha precisam ser iguais!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(telaAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void rgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rgActionPerformed

    private void btnEditaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditaActionPerformed
        // TODO add your handling code here:
        SecretariaModel secModel = new SecretariaModel();
        
        secModel.setCod(cod.getText());
        secModel.setRg(rg.getText());
        secModel.setCpf(cpf.getText());
        secModel.setEndereco(endereco.getText());
        secModel.setNome(Nome.getText());
        secModel.setSexo((String) sexo.getSelectedItem());
        
        DefaultTableModel tblSec = (DefaultTableModel) tblSecretarias.getModel();
        try {
            // TODO add your handling code here:    
            SecretariaDAO secDAO = new SecretariaDAO();
            if(tblSecretarias.getSelectedRow() != -1){
                tblSecretarias.setValueAt(cod.getText(), tblSecretarias.getSelectedRow(), 0);
                tblSecretarias.setValueAt(rg.getText(), tblSecretarias.getSelectedRow(), 1);
                tblSecretarias.setValueAt(Nome.getText(), tblSecretarias.getSelectedRow(), 2);
                tblSecretarias.setValueAt(cpf.getText(), tblSecretarias.getSelectedRow(), 3);
                tblSecretarias.setValueAt(endereco.getText(), tblSecretarias.getSelectedRow(), 4);
                tblSecretarias.setValueAt(sexo.getSelectedItem(), tblSecretarias.getSelectedRow(), 5);
                secDAO.editarSecretaria(secModel);
                JOptionPane.showMessageDialog(null, "Secretária editada com sucesso!");
            }else{
                JOptionPane.showMessageDialog(null, "Selecione a secretária antes de editar!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(telaAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditaActionPerformed

    private void btnApagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagaActionPerformed
        SecretariaModel secModel = new SecretariaModel();
        secModel.setCod(cod.getText());
        DefaultTableModel tblSec = (DefaultTableModel) tblSecretarias.getModel();
        try {
            // TODO add your handling code here:    
            SecretariaDAO secDAO = new SecretariaDAO();
            if(tblSecretarias.getSelectedRow() != -1){
                secDAO.apagarSecretaria(secModel);
                tblSec.removeRow(tblSecretarias.getSelectedRow());
                JOptionPane.showMessageDialog(null, "Secretária deletada com sucesso!");
            }else{
                JOptionPane.showMessageDialog(null, "Selecione a secretária antes de apagar!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(telaAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnApagaActionPerformed

    private void tblSecretariasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSecretariasMouseClicked
        // TODO add your handling code here:
        cod.setText(tblSecretarias.getValueAt(tblSecretarias.getSelectedRow(), 0).toString());
        rg.setText(tblSecretarias.getValueAt(tblSecretarias.getSelectedRow(), 1).toString());
        Nome.setText(tblSecretarias.getValueAt(tblSecretarias.getSelectedRow(), 2).toString());
        cpf.setText(tblSecretarias.getValueAt(tblSecretarias.getSelectedRow(), 3).toString());
        endereco.setText(tblSecretarias.getValueAt(tblSecretarias.getSelectedRow(), 4).toString());
        sexo.setSelectedItem(tblSecretarias.getValueAt(tblSecretarias.getSelectedRow(), 5).toString());
    }//GEN-LAST:event_tblSecretariasMouseClicked

    private void tblSecretariasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblSecretariasKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblSecretariasKeyPressed

    private void tblSecretariasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblSecretariasKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblSecretariasKeyTyped

    private void tblSecretariasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblSecretariasKeyReleased
        // TODO add your handling code here:
        cod.setText(tblSecretarias.getValueAt(tblSecretarias.getSelectedRow(), 0).toString());
        rg.setText(tblSecretarias.getValueAt(tblSecretarias.getSelectedRow(), 1).toString());
        Nome.setText(tblSecretarias.getValueAt(tblSecretarias.getSelectedRow(), 2).toString());
        cpf.setText(tblSecretarias.getValueAt(tblSecretarias.getSelectedRow(), 3).toString());
        endereco.setText(tblSecretarias.getValueAt(tblSecretarias.getSelectedRow(), 4).toString());
        sexo.setSelectedItem(tblSecretarias.getValueAt(tblSecretarias.getSelectedRow(), 5).toString());
    }//GEN-LAST:event_tblSecretariasKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nome;
    private javax.swing.JButton btnApaga;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnEdita;
    private javax.swing.JTextField cod;
    private javax.swing.JPasswordField confirmSenha;
    private javax.swing.JFormattedTextField cpf;
    private javax.swing.JTextField endereco;
    private javax.swing.JPanel inicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField login;
    private javax.swing.JButton logout;
    private javax.swing.JPanel medicos;
    private javax.swing.JPanel pacientes;
    private javax.swing.JTextField rg;
    private javax.swing.JPanel secretarias;
    private javax.swing.JPasswordField senha;
    private javax.swing.JComboBox sexo;
    private javax.swing.JTable tblMedico;
    private javax.swing.JTable tblPacientes;
    private javax.swing.JTable tblSecretarias;
    // End of variables declaration//GEN-END:variables
}
